# Trường Đại học Bách Khoa thành phố Hồ Chí Minh  
# Group:
Phan Gia Anh - 2270167  
Nguyễn Trường Thành - 2270084  
Nguyễn Đức Phú - 2171014  
Đoàn Trần Cao Trí (Leader) - 2010733

# Đề tài: Mô phỏng map (google map) và tìm đường đi ngắn nhất từ điểm A đến điểm B. Ngoài ra, đề xuất đường đi ngắn thứ nhì và thứ ba

##Ý tưởng: 
Dữ liệu:  
*) Địa điểm trên google map sẽ lưu về (tên, kinh độ, vĩ độ)  
*) Chuyển dữ liệu trên thành ma trận liền kề  
Giải thuật:  
*) Tìm đường đi ngắn thứ k với priority queue
Ghi chú:
*) Dữ liệu tọa độ của 1 địa điểm trên google map có thể là tọa độ điểm trung tâm tùy vào góc nhìn của bạn, nên cẩn thận để lấy chính xác tọa độ của địa điểm đó.

In [161]:
import numpy as np
import pandas as pd
import heapq #priority queue
import copy

#Lấy dữ liệu

In [162]:
df = pd.read_excel("dataset.xlsx", usecols="A", header=None)
df

                                                    0
0   LINESTRING (106.6525367 10.7902854, 106.656021...
1   LINESTRING (106.6560217 10.7779374, 106.656035...
2   LINESTRING (106.6560358 10.7778896, 106.656119...
3   LINESTRING (106.6569368 10.7760085, 106.656567...
4   LINESTRING (106.6581076 10.7704288, 106.658611...
..                                                ...
95  LINESTRING (106.6980208 10.7725168, 106.698384...
96  LINESTRING (106.6980208 10.7725168, 106.698491...
97  LINESTRING (106.6987787 10.7723107, 106.698253...
98  LINESTRING (106.6987815 10.7723253, 106.698493...
99  LINESTRING (106.6990376 10.7740459, 106.698106...

[100 rows x 1 columns]

In [163]:
num_rows = df.shape[0]
num_rows

100

In [164]:
class Point:
  ID = 0
  def __init__(self, coor):
    # self.street = src['Đường'].split(',')
    # self.name = src['Tên địa điểm']
    self.X = coor[0]
    self.Y = coor[1]
    self.ID = Point.ID
    Point.ID += 1

Points = []
Adjacency = []

def distance(p0, p1):
  return pow(pow((p0.X - p1.X),2) + pow((p0.Y - p1.Y),2), 1/2)

def find_in_Points(coor):
  if len(Points) == 0:
    return -1
  for idx in range(len(Points)):
    if Points[idx].X == coor[0] and Points[idx].Y == coor[1]:
      return idx
  return -1

for idx in range(num_rows):
  src = df.iloc(0)[idx][0]
  src = src.split(' ', 1)[1]
  src = src[1: -1]
  src = src.split(', ')

  listID = []

  for coor in src:
    coor = coor.split(' ')
    coor = [float(x) for x in coor]

    idx = find_in_Points(coor)    
    if idx == -1:
      Points.append(Point(coor))
      Adjacency.append([])
      listID.append(Points[-1].ID)
    else:
      listID.append(Points[idx].ID)
  print(listID)
  n = len(listID)
  if n >= 2:
    if not listID[1] in Adjacency[listID[0]]:
      Adjacency[listID[0]].append(listID[1])
  for i in range(1, n - 1):
    if not listID[i - 1] in Adjacency[listID[i]]:
      Adjacency[listID[i]].append(listID[i - 1])
    if not listID[i + 1] in Adjacency[listID[i]]:
      Adjacency[listID[i]].append(listID[i + 1])
  if n >= 2:
    if not listID[n - 2] in Adjacency[listID[n - 1]]:
      Adjacency[listID[n - 1]].append(listID[n - 2])

Adjacency

[0, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[2, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
[33, 34]
[19, 35, 36, 37]
[38, 39]
[38, 40]
[37, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61]
[37, 62]
[63, 64]
[65, 66]
[39, 67, 68, 19]
[39, 69, 70, 71]
[39, 62]
[72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 38]
[101, 102]
[103, 104]
[105, 106, 107, 108, 61]
[105, 109, 110, 111, 112]
[105, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126]
[62, 127, 128]
[129, 130, 131, 132]
[127, 133, 134]
[127, 128]
[135, 136]
[137, 138, 139, 140, 141, 142, 118]
[66, 143, 105]
[66, 144, 132, 134]
[145, 146, 147, 148, 129, 62]
[149, 150]
[110, 151, 66]
[128, 152, 153, 69]
[128, 154]
[155, 156, 157, 158, 159, 160, 161]
[155, 162, 163, 164, 165, 166, 167]
[71, 40]
[168, 169, 170, 171, 172, 173, 174, 72]
[175, 176]
[154, 177, 178, 179, 180, 181, 160]
[111, 182, 126]
[134, 154]
[134, 183, 184, 185, 165, 186]
[134, 187]
[187, 182]
[182, 112]
[112, 188]
[189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204]
[205, 71]
[205, 206, 207, 164, 154]
[126, 208, 188]
[126, 209, 210, 167, 211]
[126, 212, 213, 214, 215]
[216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 134]
[228, 229]
[230, 231]
[188, 232, 233, 234]
[211, 235, 236, 237, 238, 239]
[211, 214, 240, 241, 242]
[240, 243, 244, 245, 246, 247]
[239, 248, 249, 250, 251, 247]
[239, 198]
[242, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262]
[263, 264]
[247, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 200]
[247, 279, 280]
[264, 281, 282, 283]
[264, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293]
[283, 294]
[283, 295, 296, 297, 298]
[279, 256]
[279, 299, 204]
[293, 300, 301, 302]
[293, 303, 304, 305, 306, 307, 308, 309, 310, 311]
[302, 312, 313, 314, 315, 316, 317, 318]
[318, 319, 320, 321, 322, 323, 324]
[325, 326, 327, 328, 329]
[200, 330, 331, 332, 204]
[311, 333, 334]
[328, 335, 336, 337, 338]
[334, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348]
[262, 349, 350, 204]
[262, 351, 352, 353, 354, 355, 356, 357, 358, 359]
[262, 360, 348]
[351, 361]
[362, 363, 364, 365, 366, 367]
[368, 369, 370, 371, 372, 373]
[348, 374, 375, 376, 377, 378]
[370, 379, 380, 356]
[381, 367]
[379, 382]
[355, 383, 368, 384, 385, 204]
[373, 386, 382, 359]
[387, 388]
[389, 387]
[389, 390]
[389, 391]
[389, 392]
[393, 394, 359]
[395, 396, 397]
[398, 397, 399, 373]

[[1],
 [0, 2],
 [1, 3, 20],
 [2, 4],
 [3, 5],
 [4, 6],
 [5, 7],
 [6, 8],
 [7, 9],
 [8, 10],
 [9, 11],
 [10, 12],
 [11, 13],
 [12, 14],
 [13, 15],
 [14, 16],
 [15, 17],
 [16, 18],
 [17, 19],
 [18, 35, 68],
 [2, 21],
 [20, 22],
 [21, 23],
 [22, 24],
 [23, 25],
 [24, 26],
 [25, 27],
 [26, 28],
 [27, 29],
 [28, 30],
 [29, 31],
 [30, 32],
 [31],
 [34],
 [33],
 [19, 36],
 [35, 37],
 [36, 41, 62],
 [39, 40, 100],
 [38, 67, 69, 62],
 [38, 71],
 [37, 42],
 [41, 43],
 [42, 44],
 [43, 45],
 [44, 46],
 [45, 47],
 [46, 48],
 [47, 49],
 [48, 50],
 [49, 51],
 [50, 52],
 [51, 53],
 [52, 54],
 [53, 55],
 [54, 56],
 [55, 57],
 [56, 58],
 [57, 59],
 [58, 60],
 [59, 61],
 [60, 108],
 [37, 39, 127, 129],
 [64],
 [63],
 [66],
 [65, 143, 144, 151],
 [39, 68],
 [67, 19],
 [39, 70, 153],
 [69, 71],
 [70, 40, 205],
 [73, 174],
 [72, 74],
 [73, 75],
 [74, 76],
 [75, 77],
 [76, 78],
 [77, 79],
 [78, 80],
 [79, 81],
 [80, 82],
 [81, 83],
 [82, 84],
 [83, 85],
 [84, 86],
 [85, 87],
 [86, 88],
 [87, 89],
 [88, 90],
 [89, 91],
 [90, 92],
 [91, 93],
 [92, 94],
 [93, 95],
 [94, 96],
 [95, 97],
 [96, 98],
 [97, 99],
 [98, 100],
 [99, 38],
 [102],
 [101],
 [104],
 [103],
 [106, 109, 113, 143],
 [105, 107],
 [106, 108],
 [107, 61],
 [105, 110],
 [109, 111, 151],
 [110, 112, 182],
 [111, 182, 188],
 [105, 114],
 [113, 115],
 [114, 116],
 [115, 117],
 [116, 118],
 [117, 119, 142],
 [118, 120],
 [119, 121],
 [120, 122],
 [121, 123],
 [122, 124],
 [123, 125],
 [124, 126],
 [125, 182, 208, 209, 212],
 [62, 128, 133],
 [127, 152, 154],
 [130, 148, 62],
 [129, 131],
 [130, 132],
 [131, 144, 134],
 [127, 134],
 [133, 132, 154, 183, 187, 227],
 [136],
 [135],
 [138],
 [137, 139],
 [138, 140],
 [139, 141],
 [140, 142],
 [141, 118],
 [66, 105],
 [66, 132],
 [146],
 [145, 147],
 [146, 148],
 [147, 129],
 [150],
 [149],
 [110, 66],
 [128, 153],
 [152, 69],
 [128, 177, 134, 164],
 [156, 162],
 [155, 157],
 [156, 158],
 [157, 159],
 [158, 160],
 [159, 161, 181],
 [160],
 [155, 163],
 [162, 164],
 [163, 165, 207, 154],
 [164, 166, 185, 186],
 [165, 167],
 [166, 210, 211],
 [169],
 [168, 170],
 [169, 171],
 [170, 172],
 [171, 173],
 [172, 174],
 [173, 72],
 [176],
 [175],
 [154, 178],
 [177, 179],
 [178, 180],
 [179, 181],
 [180, 160],
 [111, 126, 187, 112],
 [134, 184],
 [183, 185],
 [184, 165],
 [165],
 [134, 182],
 [112, 208, 232],
 [190],
 [189, 191],
 [190, 192],
 [191, 193],
 [192, 194],
 [193, 195],
 [194, 196],
 [195, 197],
 [196, 198],
 [197, 199, 239],
 [198, 200],
 [199, 201, 278, 330],
 [200, 202],
 [201, 203],
 [202, 204],
 [203, 299, 332, 350, 385],
 [71, 206],
 [205, 207],
 [206, 164],
 [126, 188],
 [126, 210],
 [209, 167],
 [167, 235, 214],
 [126, 213],
 [212, 214],
 [213, 215, 211, 240],
 [214],
 [217],
 [216, 218],
 [217, 219],
 [218, 220],
 [219, 221],
 [220, 222],
 [221, 223],
 [222, 224],
 [223, 225],
 [224, 226],
 [225, 227],
 [226, 134],
 [229],
 [228],
 [231],
 [230],
 [188, 233],
 [232, 234],
 [233],
 [211, 236],
 [235, 237],
 [236, 238],
 [237, 239],
 [238, 248, 198],
 [214, 241, 243],
 [240, 242],
 [241, 252],
 [240, 244],
 [243, 245],
 [244, 246],
 [245, 247],
 [246, 251, 265, 279],
 [239, 249],
 [248, 250],
 [249, 251],
 [250, 247],
 [242, 253],
 [252, 254],
 [253, 255],
 [254, 256],
 [255, 257, 279],
 [256, 258],
 [257, 259],
 [258, 260],
 [259, 261],
 [260, 262],
 [261, 349, 351, 360],
 [264],
 [263, 281, 284],
 [247, 266],
 [265, 267],
 [266, 268],
 [267, 269],
 [268, 270],
 [269, 271],
 [270, 272],
 [271, 273],
 [272, 274],
 [273, 275],
 [274, 276],
 [275, 277],
 [276, 278],
 [277, 200],
 [247, 280, 256, 299],
 [279],
 [264, 282],
 [281, 283],
 [282, 294, 295],
 [264, 285],
 [284, 286],
 [285, 287],
 [286, 288],
 [287, 289],
 [288, 290],
 [289, 291],
 [290, 292],
 [291, 293],
 [292, 300, 303],
 [283],
 [283, 296],
 [295, 297],
 [296, 298],
 [297],
 [279, 204],
 [293, 301],
 [300, 302],
 [301, 312],
 [293, 304],
 [303, 305],
 [304, 306],
 [305, 307],
 [306, 308],
 [307, 309],
 [308, 310],
 [309, 311],
 [310, 333],
 [302, 313],
 [312, 314],
 [313, 315],
 [314, 316],
 [315, 317],
 [316, 318],
 [317, 319],
 [318, 320],
 [319, 321],
 [320, 322],
 [321, 323],
 [322, 324],
 [323],
 [326],
 [325, 327],
 [326, 328],
 [327, 329, 335],
 [328],
 [200, 331],
 [330, 332],
 [331, 204],
 [311, 334],
 [333, 339],
 [328, 336],
 [335, 337],
 [336, 338],
 [337],
 [334, 340],
 [339, 341],
 [340, 342],
 [341, 343],
 [342, 344],
 [343, 345],
 [344, 346],
 [345, 347],
 [346, 348],
 [347, 360, 374],
 [262, 350],
 [349, 204],
 [262, 352, 361],
 [351, 353],
 [352, 354],
 [353, 355],
 [354, 356, 383],
 [355, 357, 380],
 [356, 358],
 [357, 359],
 [358, 382, 394],
 [262, 348],
 [351],
 [363],
 [362, 364],
 [363, 365],
 [364, 366],
 [365, 367],
 [366, 381],
 [369, 383, 384],
 [368, 370],
 [369, 371, 379],
 [370, 372],
 [371, 373],
 [372, 386, 399],
 [348, 375],
 [374, 376],
 [375, 377],
 [376, 378],
 [377],
 [370, 380, 382],
 [379, 356],
 [367],
 [379, 386, 359],
 [355, 368],
 [368, 385],
 [384, 204],
 [373, 382],
 [388, 389],
 [387],
 [387, 390, 391, 392],
 [389],
 [389],
 [389],
 [394],
 [393, 359],
 [396],
 [395, 397],
 [396, 398, 399],
 [397],
 [397, 373]]

#Chuyển đổi dữ liệu sang class

Khoảng cách giữa 2 địa danh chỉ đo được khi hai địa danh nằm trên cùng 1 tuyến đường

In [165]:
class Route:
  def __init__(self, src):
    self.v = [src]
    self.len = 0
  def __lt__(self, other):
    return self.len < other.len
  def __le__(self, other):
    return self.len <= other.len
  def add(self, v, len):
    self.v.append(v)
    self.len += len
  def get_tail(self):
    return self.v[-1]
  def get_vertices(self):
    return self.v

# Thiết lập giải thuật

## Ma trận liền kề

In [166]:
# adjacency_matrix = np.zeros((df.shape[0], df.shape[0]))

# for i in range(df.shape[0]):
#   for j in range(df.shape[0]):
#     if i > j:
#       adjacency_matrix[i][j] = adjacency_matrix[j][i]
#     else:
#       adjacency_matrix[i][j] = positions[i].dist2(positions[j])

# adjacency_matrix[0]

## Implement Pririty Queue

In [167]:
# A simple implementation of Priority Queue
# using Queue.
class PriorityQueue(object):
	def __init__(self):
		self.queue = []

	def __str__(self):
		return ' '.join([str(i) for i in self.queue])

	# for checking if the queue is empty
	def isEmpty(self):
		return len(self.queue) == 0

	# for inserting an element in the queue
	def push(self, data):
		self.queue.append(data)

	# for popping an element based on Priority
	def pop(self):
		try:
			min_val = 0
			for i in range(len(self.queue)):
				if self.queue[i] < self.queue[min_val]:
					min_val = i
			item = self.queue[min_val]
			del self.queue[min_val]
			return item
		except IndexError:
			print()
			exit()

In [168]:
# adjacency_matrix = [
#     [0, 2, 6, -1, 4],
#     [2, 0, 3, 5, -1],
#     [6, 3, 0, 1, -1],
#     [-1, 5, 1, 0, 2],
#     [4, -1, -1, 2, 0]
# ]

def flow_from_A_to_B(start, end, k = 3):
  # if (not start in range(df.shape[0])) or (not end in range(df.shape[0])):
  #   print('Điểm xuất phát hoặc điểm đến không hợp lệ')
  #   return []
  # k = min(max(3, k), 10)
  result = []
  cnt = np.zeros(len(Points))
  pq = PriorityQueue()
  pq.push(Route(start))
  # heapq.heappush(pri_queue, ) #length, link_list

  while not pq.isEmpty() and cnt[end] < k:
    shortest = pq.pop()
    u = shortest.get_tail()
    # print(shortest)
    cnt[u] += 1
    if (u == end):
      result.append(shortest)
    if cnt[u] <= k:
      # print(len(Adjacency[u]))
      for i in range(len(Adjacency[u])):
        v = Adjacency[u][i]
        dist = distance(Points[v], Points[u])
        # if adjacency_matrix[u][i] == -1:
        if not v in shortest.get_vertices():
          new_route = copy.deepcopy(shortest)
          new_route.add(v, dist)
          # print(new_route.v)
          pq.push(new_route)
  return result

#Main function

##Nhận dữ liệu đầu vào

Tên địa danh được copy từ google map

In [169]:
def isTheyAreOne(des0, des1):
  des0 = des0.lower()
  des1 = des1.lower()

  if (des0 == des1):
    return True
  if (des0 in des1) or (des1 in des0):
    return True
  return False

In [170]:
df_des = pd.read_excel("destination.xlsx", usecols="A:C")
df_des

                               Tên địa điểm          x           y
0                          Adora Grand View  10.758082  106.668034
1   Bảo tàng Mỹ thuật Thành phố Hồ Chí Minh  10.770341  106.699576
2                        Bệnh viện Bình Dân  10.774194  106.681281
3                         Bệnh viện Chợ Rẫy  10.757801  106.659546
4           Bệnh viện Đại học Y Dược TP.HCM  10.755425  106.664646
..                                      ...        ...         ...
64                            Vạn Hạnh Mall  10.770768  106.669936
65               Viettel 312 Lý Thường Kiệt  10.768525  106.658829
66      Vòng xoay An Dương Vương - Trần Phú  10.757516  106.674076
67                       Vòng xoay Hòa Bình  10.766823  106.642373
68                    Vòng xoay Lê Đại Hành  10.769038  106.652268

[69 rows x 3 columns]

In [171]:
# source_name = input('Điểm khởi đầu của bạn là: ')
# destination_name = input('Đích đến của bạn là: ')
source_name = "Trường Đại học bách Khoa"
destination_name = "Chợ Bến Thành"
start = -1
end = -1

k = 3

namePlace = df_des['Tên địa điểm'].tolist()

for idx, x in enumerate(namePlace):
  if isTheyAreOne(x, source_name):
    start = idx
  if isTheyAreOne(x, destination_name):
    end = idx
# namePlace
print(start, end)

start = df_des.iloc(0)[start]
end = df_des.iloc(0)[end]

start = Point([float(start[2]), float(start[1])])
end = Point([float(end[2]), float(end[1])])

def get_closest_point(marker):
  minVal = 99999
  minIndex = 0
  for p in Points:
    tmp = distance(marker, p)
    if minVal > tmp:
      minVal = tmp
      minIndex = p.ID
  return minIndex

closest_start = get_closest_point(start)
closest_end = get_closest_point(end)

print(closest_start, closest_end)

55 17
15 397

##Kết quả

In [172]:
result = flow_from_A_to_B(closest_start, closest_end, 3)

# result.sort(key= lambda x: x.len)
print(result)

[<__main__.Route object at 0x7f980fe4cb90>, <__main__.Route object at 0x7f980fe4c510>, <__main__.Route object at 0x7f980fe4c810>]

In [173]:
# """## Lưu trữ"""
# f = open("result.txt", "w")
# for res in result:
#   f.write(str(start.X) + ' ' + str(start.Y) + '\n')
#   for v in res.v:
#     f.write(str(Points[v].X) + ' ' + str(Points[v].Y) + '\n')
#   f.write(str(end.X) + ' ' + str(end.Y) + '@\n')
#   # f.write('@\n')
# f.write('@\n')
# f.close()